const $=(selector,root=document)=>root.querySelector(selector);
const esc=value=>String(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const arrow='<span aria-hidden="true">↗</span>';

async function start(){
  const response=await fetch('./data.json');
  if(!response.ok)throw new Error(`İçerik yüklenemedi: ${response.status}`);
  const data=await response.json();
  const sectionHead=(section)=>`<div class="section-head reveal"><span class="section-number">/${esc(section.index)}</span><div class="section-title"><div class="eyebrow">${esc(section.kicker)}</div><h2>${esc(section.title)}</h2></div></div>`;
  $('#app').innerHTML=`
    <header class="header"><div class="header-inner wrap"><a class="brand" href="#top"><img src="assets/logo-mark.svg" alt=""><span><b>${esc(data.brand.shortName)}</b><small>İNŞAAT</small></span></a><nav class="nav" id="nav" aria-label="Ana menü">${data.navigation.map(item=>`<a href="${esc(item.href)}">${esc(item.label)}</a>`).join('')}</nav><a class="header-call" href="${esc(data.brand.phoneHref)}"><span>PROJENİZİ KONUŞALIM</span><strong>${esc(data.brand.phone)}</strong></a><button class="menu-button" aria-controls="nav" aria-expanded="false">Menü</button></div></header>
    <main id="main"><section class="hero" id="top"><div class="hero-grid wrap"><div class="hero-copy"><div class="eyebrow">${esc(data.hero.kicker)}</div><h1>${formatHero(data.hero.title)}</h1><p class="hero-description">${esc(data.hero.description)}</p><div class="hero-actions"><a class="button" href="${esc(data.brand.whatsapp)}" target="_blank" rel="noopener noreferrer">${esc(data.hero.primaryCta)} ${arrow}</a><a class="text-link" href="#hizmetler">${esc(data.hero.secondaryCta)} ↓</a></div><div class="proof-row">${data.hero.proof.map(item=>`<span class="proof">${esc(item)}</span>`).join('')}</div></div><div class="build-visual" aria-hidden="true"><div class="building"><div class="floor floor-1"><span></span></div><div class="floor floor-2"><span></span></div><div class="floor floor-3"><span></span></div><div class="floor floor-4"></div></div><div class="crane"></div><span class="visual-label">${esc(data.hero.visualLabel)}</span></div></div><span class="scroll-cue">AŞAĞI KAYDIR</span></section>
    <section class="section wrap">${sectionHead(data.intro)}<div class="intro-grid reveal"><p>${esc(data.intro.body)}</p><div class="intro-note">${esc(data.intro.note)}<br><strong>${esc(data.brand.slogan)}</strong></div></div></section>
    <section class="section services" id="hizmetler"><div class="wrap">${sectionHead(data.services)}<div class="service-list">${data.services.items.map(item=>`<article class="service-row reveal"><small>${esc(item.number)}</small><h3>${esc(item.title)}</h3><p>${esc(item.description)}</p><span class="service-icon" aria-hidden="true">↗</span></article>`).join('')}</div></div></section>
    <section class="section projects" id="projeler"><div class="wrap projects-head"><div>${sectionHead(data.projects)}</div><p>${esc(data.projects.description)}</p></div><div class="route-shell"><div class="route-line"></div><div class="project-route" tabindex="0" aria-label="Proje rotası">${data.projects.items.map((item,index)=>projectCard(item,index)).join('')}</div><div class="route-controls"><button data-route="prev" aria-label="Önceki proje">←</button><button data-route="next" aria-label="Sonraki proje">→</button></div>${data.projects.media.length?renderMedia(data.projects.media):'<p class="empty-media">Fotoğraf ve video klasörleri hazır. Gerçek medya eklendiğinde arşiv burada otomatik gösterilecek.</p>'}</div></section>
    <section class="section wrap" id="surec">${sectionHead(data.process)}<div class="process-grid">${data.process.steps.map((step,index)=>`<article class="process-step reveal"><span>0${index+1}</span><h3>${esc(step.title)}</h3><p>${esc(step.description)}</p></article>`).join('')}</div><div class="faq"><h2>${esc(data.faq.title)}</h2><div>${data.faq.items.map((item,index)=>`<details ${index===0?'open':''}><summary>${esc(item.question)}</summary><p>${esc(item.answer)}</p></details>`).join('')}</div></div></section>
    <section class="contact" id="iletisim"><div class="wrap"><div class="contact-grid"><div><div class="eyebrow">${esc(data.contact.kicker)}</div><h2>${esc(data.contact.title)}</h2><p>${esc(data.contact.description)}</p></div><div class="contact-actions"><a class="button button-light" href="${esc(data.brand.whatsapp)}" target="_blank" rel="noopener noreferrer">${esc(data.contact.primaryCta)} ${arrow}</a><span>${esc(data.contact.phoneLabel)}</span><a class="contact-phone" href="${esc(data.brand.phoneHref)}">${esc(data.brand.phone)}</a></div></div><div class="contact-meta"><span>${esc(data.contact.address)}</span><span>${esc(data.contact.hours)}</span></div><footer class="footer"><span>${esc(data.contact.copyright)}</span><a href="#top">Başa dön ↑</a></footer><div class="developer-credit"><span>${esc(data.contact.developer.label)} <a href="${esc(data.contact.developer.website)}" target="_blank" rel="noopener noreferrer"><strong>${esc(data.contact.developer.name)}</strong></a></span><div><a href="${esc(data.contact.developer.phoneHref)}">${esc(data.contact.developer.phone)}</a><a href="${esc(data.contact.developer.instagram)}" target="_blank" rel="noopener noreferrer">${esc(data.contact.developer.instagramLabel)} ↗</a></div></div></div></section></main>`;
  initMenu();initRoute();initReveals();
}

function formatHero(title){const words=esc(title).split(' ');const key=words.splice(-2).join(' ');return `${words.join(' ')} <em>${key}</em>`;}
function projectCard(item,index){const color=['#bb5a2b','#d68b51','#927357','#cf6b35'][index%4];return `<figure class="project-card"><div class="route-stop"></div><div class="project-visual ${item.image?'has-image':''}" style="--card:${color}">${item.image?`<img src="${esc(item.image)}" alt="${esc(item.title)}" loading="lazy">`:''}<span class="project-tag">${esc(item.category)}</span></div><figcaption><div><h3>${esc(item.title)}</h3><small>${esc(item.location)}</small></div><time>${esc(item.year)}</time></figcaption></figure>`;}
function renderMedia(items){return `<div class="media-archive">${items.map(item=>item.type==='video'?`<video src="${esc(item.src)}" poster="${esc(item.poster)}" muted playsinline controls></video>`:`<img src="${esc(item.src)}" alt="${esc(item.title)}" loading="lazy">`).join('')}</div>`;}
function initMenu(){const button=$('.menu-button'),nav=$('.nav');button.onclick=()=>{const open=button.getAttribute('aria-expanded')!=='true';button.setAttribute('aria-expanded',String(open));button.textContent=open?'Kapat':'Menü';nav.classList.toggle('open',open);document.body.classList.toggle('menu-open',open)};nav.onclick=()=>{button.setAttribute('aria-expanded','false');button.textContent='Menü';nav.classList.remove('open');document.body.classList.remove('menu-open')};}
function initRoute(){const route=$('.project-route'),line=$('.route-line');const move=direction=>route.scrollBy({left:direction*route.clientWidth*.72,behavior:'smooth'});$('[data-route="prev"]').onclick=()=>move(-1);$('[data-route="next"]').onclick=()=>move(1);const update=()=>{const max=route.scrollWidth-route.clientWidth;line.style.setProperty('--route-progress',max?route.scrollLeft/max:1)};route.addEventListener('scroll',update,{passive:true});update();}
function initReveals(){const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;if(reduced){document.querySelectorAll('.reveal').forEach(el=>el.classList.add('in'));return}const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in');observer.unobserve(entry.target)}}),{threshold:.14,rootMargin:'0px 0px -7%'});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));}

start().catch(error=>{console.error(error);$('#app').innerHTML='<div class="loading"><h1>Diler İnşaat</h1><p>İçerik yüklenemedi. Yerel önizleme için projeyi bir HTTP sunucusu üzerinden açın.</p><a href="tel:+905354024773">+90 535 402 47 73</a></div>';});
